production:
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

development:
  secret_token: <%= ENV['DEVELOPMENT_SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['DEVELOPMENT_SECRET_KEY_BASE'] %>

test:
  secret_token: <%= ENV['TEST_SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['TEST_SECRET_KEY_BAS'] %>

