production:
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

development:
  secret_token: "my_secret_token"
  secret_key_base: "abcdef0123456789"

test:
  secret_token: "test_secret_token"
  secret_key_base: "54a8dfk890dsd43howkw92p1s0qk24732j"

